### ISSUE TITLE
Term RFC: [version]

### ISSUE THREAD

**Issue by chimotono** [rust-arabia/ar-en-computing-terms#45]
أنا مقدم الطلب أقترح إضافة المصطلحات التالية

- version

التي تستخدم في سياقات التالية:

- سياق
- سياق آخر

إن الدوافع التي تبرر إضافة هذه المصطلحات هي:

- دافع
- دافع آخر

**Comment by sam-ka** [comment]
An issue for this term has already been opened. See issue #3
